truncate table products;

insert into products(code, name, description, image_url, price) values
                    ('P100','Confabulations','''Language is a body, a living creature ... and this creature''s home is the inarticulate as well as the articulate''. John Berger''s work has revolutionized the way we understand visual language. In this new book he writes about language itself, and how it relates to thought, art, song, storytelling and political discourse today. Also containing Berger''s own drawings, notes, memories and reflections on everything from Albert Camus to global capitalism, Confabulations takes us to what is ''true, essential and urgent''.','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1475878710l/32496468._SY475_.jpg',25.00),
                    ('P101','Ways of Seeing',' He is a liberator of images: and once we have allowed the paintings to work on us directly, we are in a much better position to make a meaningful evaluation" —Peter Fuller, Arts Review "The influence of the series and the book . . . was enormous . . . It opened up for general attention to areas of cultural study that are now commonplace"','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1703328414l/2784._SY475_.jpg',15.00),
                    ('P103','Face Off (D.C. Stars, #1)','He’s a notorious playboy who doesn’t date. Period. Except… what should’ve been just once happens again, then again. They tell each other their friends with benefits arrangement is only for the season, but despite facing off on the ice, behind closed doors, the pair is nothing but fire','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1716408331l/213779197._SY475_.jpg',50.00),
                    ('P104','Steve Jobs','Walter Isaacson''s worldwide bestselling biography of Apple cofounder Steve Jobs. Based on more than forty interviews with Steve Jobs conducted over two years--as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues--Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. Isaacson''s portrait touched millions of readers','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1511288482l/11084145._SY475_.jpg',45.50),
                    ('P105','Elon Musk','From the author of Steve Jobs and other bestselling biographies, this is the astonishingly intimate story of the most fascinating and controversial innovator of our era—a rule-breaking visionary who helped to lead the world into the era of electric vehicles, private space exploration, and artificial intelligence','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1692288251l/122765395._SY475_.jpg',25.45),
                    ('P106','Zero to One',': Notes on Startups, or How to Build the Future','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630663027l/18050143.jpg',12.45),
                    ('P107','Shoe Dog','A Memoir by the Creator of Nike','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1457284880l/27220736.jpg',35.00),
                    ('P108','The Lean Startup','Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched. Eric Ries defines a startup as an organization dedicated to creating something new under conditions of extreme uncertainty','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629999184l/10127019._SY475_.jpg',15.50),
                    ('P109','Dracula','You can find an alternative cover edition for this ISBN here and here. When Jonathan Harker visits Transylvania to help Count Dracula with the purchase of a London house, he makes a series of horrific discoveries about his client. Soon afterwards, various bizarre incidents unfold in England: an apparently unmanned ship is wrecked off the coast of Whitby; a young woman discovers strange puncture marks on her neck; and the inmate of a lunatic asylum raves about the ''Master'' and his imminent arrival. In Dracula, Bram Stoker created one of the great masterpieces of the horror genre, brilliantly evoking a nightmare world of vampires and vampire hunters and also illuminating the dark corners of Victorian sexuality and desire.','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387151694l/17245.jpg',9.25),
                    ('P110','Successful Aging','A Neuroscientist Explores the Power and Potential of Our Lives','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1566099456l/46114266.jpg',21.25),
                    ('P111','The New Drawing on the Right Side of the Brain','When Drawing on the Right Side of the Brain was first published in 1979, it hit the New York Times bestseller list within two weeks and stayed there for more than a year. In 1989, when Dr. Betty Edwards revised the book, it went straight to the Times list again. Now Dr. Edwards celebrates the twentieth anniversary of her classic book with a second revised edition','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348133732l/627206.jpg',24.00),
                    ('P112','Art and Fear','Korean translation of Art and Fear by David Bayles','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1442712080l/187633._SY475_.jpg',45.00),
                    ('P113','A Brief History of Time','A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends? Told in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1333578746l/3869.jpg',13.25),
                    ('P114','A Short History of Nearly Everything','Bill Bryson describes himself as a reluctant traveller, but even when he stays safely at home he can''t contain his curiosity about the world around him. "A Short History of Nearly Everything" is his quest to understand everything that has happened from the Big Bang to the rise of civilisation - how we got from there, being nothing at all, to here, being us. The ultimate eye-opening journey through time and space, revealing the world in a way most of us have never seen it before','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1433086293l/21._SY475_.jpg',35.00);